Add Simulator features: shake; motor speed
morikatron/toio-sdk-for-unity pull request #69
Opened 2020-10-22 10:09 UTC by MrkKSen

2020-10-26 04:49 UTC, ma2bara requested changes
コードについては特に問題は見つかりませんでした。
わかりやすいコーディングで良いと思いました。

コメントについて２点修正したほうがいいかな？と思いましたので修正を依頼します。
「コアキューブ」→「キューブ」
「ポーズ」→「姿勢」または「姿勢検出」

2020-10-26 04:49 UTC, ma2bara commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Sim/CubeUnity.cs
> +        private void Recv_Shake(bool shake) // コアキューブのシェイク
コアキューブ→キューブ

2020-10-26 04:49 UTC, ma2bara commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Sim/CubeUnity.cs
> +        private void Recv_Sloped(bool sloped) // コアキューブの傾き状態
コアキューブ　→　キューブ　（以下同文たくさん……

2020-10-26 04:49 UTC, ma2bara commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Simulator/CubeSimulator.cs
> +        /// ポーズ
ポーズ　→　姿勢検出　としたほうが親切（toioの仕様書にある言葉を使った方がわかりやすいので）

2020-10-26 05:30 UTC, jyo-u reviewed
問題ありません

2020-10-26 08:04 UTC, ma2bara approved these changes

2020-10-26 08:04 UTC, merged

2020-10-28 03:46 UTC, MrkKSen commented
既にマージされたので、コメントについては別ブランチで作業します。