Develop add double tap interval
morikatron/toio-sdk-for-unity pull request #74
Opened 2020-10-27 06:46 UTC by jyo-u

2020-10-28 01:22 UTC, morika-shomma requested changes
修正とデバッグをお願いします。

2020-10-28 01:22 UTC, morika-shomma commented on docs/usage_cube.md
> +public void  ConfigDoubleTapInterval(int level, ORDER_TYPE order=ORDER_TYPE.Strong);
変数名について、int levelではなく、int interval?などに変数名を変更した方が良さそうに思います。

2020-10-28 01:22 UTC, morika-shomma commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Cube.cs
> +        public virtual void ConfigDoubleTapInterval(int level, ORDER_TYPE order = ORDER_TYPE.Strong) { UnsupportedWarning(); }
変数名について、int levelではなく、int interval?などに変数名を変更した方が良さそうに思います。

2020-10-28 01:22 UTC, morika-shomma commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Real/Versions/CubeReal_ver2_1_0.cs
> +            buff[0] = 17;
0x17は十進数で23になります。

2020-11-16 05:55 UTC, morika-shomma approved these changes
確認および修正しました

2020-11-16 07:20 UTC, MrkKSen commented on docs/usage_cube.md
> +public void  ConfigDoubleTapInterval(int level, ORDER_TYPE order=ORDER_TYPE.Strong);
これは結局変えなくていいですか？

2020-11-16 07:20 UTC, MrkKSen commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Real/Versions/CubeReal_ver2_2_0.cs
> +        private bool isInitialized = false;
"isInitialized"という変数はこのクラスのプライベート変数じゃなく、CubeRealのprotectedとかにしたほうがいいかなと思いますが、ご検討を。

2020-11-16 07:51 UTC, morika-shomma commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Real/Versions/CubeReal_ver2_2_0.cs
> +        private bool isInitialized = false;
現時点では「Initialize関数の終了判定」を行う必要があるクラスは2.2.0クラスのみなので、このままprivate変数にする予定です

2020-11-16 08:16 UTC, jyo-u commented on docs/usage_cube.md
> +public void  ConfigDoubleTapInterval(int level, ORDER_TYPE order=ORDER_TYPE.Strong);
修正しました

2020-11-16 08:33 UTC, MrkKSen approved these changes

2020-11-16 08:33 UTC, merged