Develop real integrated command
morikatron/toio-sdk-for-unity pull request #97
Opened 2020-11-17 07:30 UTC by jyo-u

2020-11-17 07:33 UTC, jyo-u reviewed
余分なボタンを一つ消しました。

2020-11-17 09:23 UTC, MrkKSen requested changes

2020-11-17 09:23 UTC, MrkKSen commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Cube.cs
> +        public enum PriorityType
ユーザーが使う場合、Cube.PriorityType のようになりますね。
これは一見キューブ全体の何らかの優先度に勘違いする可能性があると思います。
これ以外のEnumも含めて、何かのプレフィックスをつけるのはどうでしょうか。

2020-11-17 09:23 UTC, MrkKSen commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Real/Versions/CubeReal_ver2_1_0.cs
> +        public override void TargetMove(int targetX, int targetY, int targetAngle, ORDER_TYPE order, params object[] paraList)
多分行き違いがありますが、前回のMTGでは、構造体を使うっていう話になりました。
object[]だと、ユーザーから何を入れればいいか、仕様書参照しながら書く必要があるので、間違いやすいし面倒です。

2020-11-17 09:23 UTC, MrkKSen commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Real/Versions/CubeReal_ver2_1_0.cs
> +        public override void AccelerationMove(int targetSpeed, int Acceleration, ORDER_TYPE order, params object[] paraList)
同上

2020-11-18 07:48 UTC, morika-shomma requested changes

2020-11-19 03:54 UTC, MrkKSen commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Cube.cs
> +                                    ORDER_TYPE order = ORDER_TYPE.Strong,
targetとORDER_TYPEは入れないほうがいいかなと個人的に思います。
targetは目標付きモーター制御機能を使う限り、必ず指定するので、関数の引数として明示的に指定する方が便利。
ORDER_TYPEはキューブに送る指令じゃないので、この構造体に入れるのは違和感あります。
つまり、関数はこのようにしたほうがいいかなと思います↓ （便利のためオーバーロードをいくつか用意するのも親切）
TargetMove(Vector2Int targetPos, int targetAngle, ORDER_TYPE order=ORDER_TYPE.Strong)
TargetMove(int targetX, int targetY, int targetAngle, ORDER_TYPE order=ORDER_TYPE.Strong)
TargetMove(Vector2Int targetPos, int targetAngle, TargetMoveConfig config, ORDER_TYPE order=ORDER_TYPE.Strong)
TargetMove(int targetX, int targetY, int targetAngle, TargetMoveConfig config, ORDER_TYPE order=ORDER_TYPE.Strong)
@morika-shomma の意見も伺いたいです。

2020-11-19 04:32 UTC, MrkKSen commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Cube.cs
> +            notRotated=5,                 // 回転しない
notRotate?

2020-11-19 04:33 UTC, MrkKSen commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Cube.cs
> +            AddRefuse=7         // 書き込み操作の追加ができない時
refused?

2020-11-19 05:48 UTC, jyo-u commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Cube.cs
> +                                    ORDER_TYPE order = ORDER_TYPE.Strong,
修正しました

2020-11-19 05:48 UTC, jyo-u commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Cube.cs
> +            notRotated=5,                 // 回転しない
修正しました

2020-11-19 05:50 UTC, jyo-u commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Cube.cs
> +            AddRefuse=7         // 書き込み操作の追加ができない時
修正しました

2020-11-19 05:59 UTC, jyo-u commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Real/Versions/CubeReal_ver2_1_0.cs
> +        public override void TargetMove(int targetX, int targetY, int targetAngle, ORDER_TYPE order, params object[] paraList)
修正しました

2020-11-19 05:59 UTC, jyo-u commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Cube.cs
> +        public enum PriorityType
修正しました

2020-11-19 05:59 UTC, jyo-u commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Real/Versions/CubeReal_ver2_1_0.cs
> +        public override void AccelerationMove(int targetSpeed, int Acceleration, ORDER_TYPE order, params object[] paraList)
修正しました

2020-11-19 08:10 UTC, MrkKSen commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Cube.cs
> +                                    ORDER_TYPE order = ORDER_TYPE.Strong,
目標の引数についてはどう思いますか？

2020-11-19 09:26 UTC, MrkKSen approved these changes

2020-11-19 09:28 UTC, MrkKSen commented on toio-sdk-unity/Assets/toio-sdk/Scripts/Cube/CoreCube/Cube.cs
> +        public virtual int motorConfigID {
後で修正することにしますので、一回取り消します。

2020-11-19 09:28 UTC, morika-shomma approved these changes

2020-11-19 09:29 UTC, merged